### Site Settings ###
title               : Kunal Mehta
description         : "I love, both, to build things and to break them."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : kunalmehta/kunalmehta.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
author              : Kunal Mehta

### Plugins ###
plugins:
  - jemoji
  - jekyll-feed

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Kunal Mehta
  image             : assets/profile.png
  # behance           : your_username
# dribbble          : your_username
  email             : kunal07@somaiya.edu
  # facebook          : kunal
  github            : kunakl07
# gitlab            : your_username
#  instagram         : vikasgola2015
#  linkedin          : vikas-gola-4a45b4135
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : vikasgola2015
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
